modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/xHyroM/seasonal-letsdo"
license = "Apache-2.0"

[[mods]]
modId = "seasonal_lets_do"
version = "${version}"
displayName = "Seasonal Let's Do"
authors = "xHyroM"
description = '''
Adds compatibility for Let's Do and Serene Seasons.
'''
logoFile = "pack.png"

[[dependencies.seasonal_lets_do]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seasonal_lets_do]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"
